[build]
  base = "frontend"
  publish = "frontend/dist"
  command = "npm install && npm run build"

# Handle SPA routing with React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 